### ISSUE TITLE
Independent disk Implementation

### ISSUE THREAD

**Issue by ty2** [vmware/go-vcloud-director#103]
Independent disk operations are missing in go-vcloud-director:
Missing Operations:
* Create Disk
* Update Disk
* Delete Disk
* Attach Disk
* Detach Disk

**Comment by hodgesrm** [comment]
Hi @ty2, fully agree. We have scheduled work to release a resource to handle independent disks during the next couple of months. 

p.s., Let us know if you are interested in contributing golang code directly for this or other features.

**Comment by hodgesrm** [comment]
OK, just saw your PR https://github.com/vmware/go-vcloud-director/pull/104.  We'll have a look.  Thanks!

**Comment by ty2** [comment]
@lvirbalas  Yes, I hv seen a lot of valuable feedback from you guys and will reply you guys very soon :)

The error message shows `types.Disk` is missing when compiling. It's most likely your local `types` package is using the origin `types` package instead of my master, so please sure using my master `types` package for compiling too. :)

**Comment by lvirbalas** [comment]
@ty2 code has been merged to vmware-takes-ownership branch! I'm closing this issue, don't hesitate to reopen if needed.
