### ISSUE TITLE
Calls to retrieve vdc entities return stale results

### ISSUE THREAD

**Issue by dataclouder** [vmware/go-vcloud-director#105]
The call to `vdc.FindVDCNetwork` will return stale results if the `vdc` entity was not updated after the network creation.

Example: 

1. `vdc` creates the network `dummy`.
2. immediately after the creation, a call to `vdc.FindVDCNetwork("dummy")` will return an error.

The reason is that the implementation of `FindVDCNetwork` will walk through `vdc` internal links, which were not updated after the network creation.
The same problem happens with most of the calls in the `vdc` module.

A call to `vdc.Refresh()` within the function should solve the problem.

**Comment by hodgesrm** [comment]
The downside of making the automatic call is you might not need it or might make multiple refresh calls before the client actually needs the links.  Example:  client program creates several networks and only examines them at the end. 

I must confess I have struggle with this issue for a while.  There does not seem to be an ideal way to handling refreshing the links.  Whatever approach we choose should be consistent across the library.

**Comment by dataclouder** [comment]
My proposal is to add the refresh in the `Find*` functions, to make sure that the vdc is up to date when it searches for entities. Some of the calls use this method. Others don't, and this is where I found the stale entities.
