### ISSUE TITLE
An AdminOrg owned by an org administrator fails to retrieve VDCs

### ISSUE THREAD

**Issue by dataclouder** [vmware/go-vcloud-director#109]
Given an organization (other than System) where the user is an org administrator, a call to `GetVdcByName` will fail with an out-of-range index.

The error happens at line 215 of org.go
```
func (adminOrg *AdminOrg) GetVdcByName(vdcname string) (Vdc, error) {
	for _, vdcs := range adminOrg.AdminOrg.Vdcs.Vdcs {
		if vdcs.Name == vdcname {
			splitbyAdminHREF := strings.Split(vdcs.HREF, "/admin")
			vdcHREF := splitbyAdminHREF[0] + splitbyAdminHREF[1]
```
We assume that the org HREF contains "/admin", but don't check if this is true.

**Comment by vbauzysvmware** [comment]
@dataclouder  I think this bug already fixed by other fixes

**Comment by dataclouder** [comment]
Fixed within a different refactoring
