### ISSUE TITLE
Enable Travis builds for project

### ISSUE THREAD

**Issue by hodgesrm** [vmware/go-vcloud-director#12]
Add Travis build to run go build as well as check formatting of code.  The following should generate build failures and block PRs: 

- Code fails to build
- go fmt generates changes on the code (i.e., the code did not have go fmt run on it before commit; see https://stackoverflow.com/questions/42510140/check-golang-format-for-continous-integration for an example of how to verify)

For this to work the project must be a public repo.  Here's one of a number of articles on Travis CI/Github integration:  https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7

**Comment by dataclouder** [comment]
Travis integration has been established.
However, I leave this issue open until we have a reliable test suite that we can trigger from TravisCI jobs.

**Comment by dataclouder** [comment]
The integration is ready and it has been proven. 
When the test suite can use a public vCD server, we we only need to add an encrypted file with the server's credentials for the test to run. I leave that task for another issue ( #90 ) .
