### ISSUE TITLE
Joining community without a PR

### ISSUE THREAD

**Issue by gregswift** [vmware/go-vcloud-director#120]
Hey all.

My team is a heavy user of the terraform-provider-vcd module, which builds atop this library.  We are tracking the work, and hoping to contributor more.  I was reading through the contributor guidelines and it shows that you have a slack channel for that work but the only way i can see to trigger the CLA is with a PR.

So my questions are:

* How do you trigger a CLA signing request?
* How do you get onto vmwarecode.slack.com

thanks!

**Comment by lvirbalas** [comment]
Hi @gregswift 

Please follow these guidelines on how to sign CLA:

> VMware Apache-licensed projects require all contributors to sign a CLA. Visit https://cla.vmware.com and follow steps presented there.

Let us know if this helps or are you looking for something else!

**Comment by lvirbalas** [comment]
Hi @gregswift , sorry. I made a wrong assumption that the submission is possible through that portal and was just not visible to me (from within VMware).

Please help me understand your needs better. You want to contribute code? The easiest way is to actually generate a PR, which will trigger VMware CLA Bot, which will generate and send you a link for signing the CLA. Can you do this? The PR can be very small. Note that each contributor needs to sign the CLA individually.

**Comment by Didainius** [comment]
@gregswift, I'm closing this issue for now. Feel free to reopen if there is still something unclear.
Thanks
