### ISSUE TITLE
implement external network operations

### ISSUE THREAD

**Issue by dataclouder** [vmware/go-vcloud-director#129]
To make a VDC immediately useful, we need the ability of creating/deleting/updating an external network.

References: 
* [External Network type](https://code.vmware.com/apis/287/vcloud#/doc/doc/types/ExternalNetworkType.html)

**Comment by lvirbalas** [comment]
Thank you for this issue, @dataclouder 
Please post a suggested Terraform resource definition too.

**Comment by megalord** [comment]
I'll take a shot at this one!
