### ISSUE TITLE
Catalog CRUD implementation 

### ISSUE THREAD

**Issue by auppunda** [vmware/go-vcloud-director#13]
Need Create, Read, Update, Delete for catalogs. This will follow the format of the org crud as we want to keep implementations consistent across the project

**Comment by lvirbalas** [comment]
@vbauzysvmware putting this effort into your attention, as you are working on a one-level-deeper implementation of Catalog Item upload, which requires a Catalog to be created first.

**Comment by vbauzysvmware** [comment]
CRUD implemented
