### ISSUE TITLE
VDC CRUD implementation

### ISSUE THREAD

**Issue by auppunda** [vmware/go-vcloud-director#14]
Similar to org and catalogs, we need to be able to create, read, update, delete vdcs

**Comment by lvirbalas** [comment]
@auppunda I believe you have started coding this effort locally. Please post a small update where you stand and what challenges, if any, are you hitting.

**Comment by auppunda** [comment]
Still sorting out xml issues with the create. I already have delete vdcs and get vdcs. Do not have update.

**Comment by lvirbalas** [comment]
Now tracked in #117
