### ISSUE TITLE
CatalogItem Crud implemenation

### ISSUE THREAD

**Issue by auppunda** [vmware/go-vcloud-director#16]
Similarly to Org, Catalog, Vdc, we need create, read, update, delete methods for catalogitems.

**Comment by lvirbalas** [comment]
@vbauzysvmware has started implementing Catalog Item upload functionality. @auppunda did you start working on this Issue #16 or shall @vbauzysvmware take it from here, as he is working on the upload?

**Comment by auppunda** [comment]
@vbauzysvmware should take it from here

**Comment by vbauzysvmware** [comment]
Implementation are in master.
