### ISSUE TITLE
vCD object data structures are not thread-safe

### ISSUE THREAD

**Issue by Didainius** [vmware/go-vcloud-director#180]
vCD object data structures (like vApp, VM, etc) are not thread-safe and one can have data race problems if operations are run concurrently (in goroutines). At the moment one has to avoid using goroutines or any other concurrent way to access structures.

This needs some bigger thoughts and wider discussion, but from the top of my head there are a few potential solutions:
* Use mutex locks to avoid multiple actions to update data structure at the same time. (And maybe consider to make these objects as singletons)
* Rethinking structure and maybe use value semantics instead of pointer semantics (doesn't seem to be the nicest thing, but noting for further thoughts).

**Comment by lvirbalas** [comment]
Please provide more details on:
- Which data structures?
- What are possible solution?

**Comment by Didainius** [comment]
Sorry. I've added more details to title and issue description rather than getting it lost in the thread.

**Comment by lvirbalas** [comment]
Awesome!
CC @vbauzysvmware

**Comment by vbauzysvmware** [comment]
At moment my mind is main approach would be create singleton for vapp, edge gtw and other required resources and be gatekeeper that only one object could be created and then on funtion level locks could be used to sync multi access.

**Comment by vbauzysvmware** [comment]
I think we don't have this issue anymore after redoing rationalization? @Didainius

**Comment by Didainius** [comment]
This issue is no longer valid as we have decided that the user of this library must understand of what can use parallelism, and what can not. https://github.com/terraform-providers/terraform-provider-vcd is one example how one can deal with parallelism.
