### ISSUE TITLE
vapp.AddVM needs to accept a storage profile

### ISSUE THREAD

**Issue by dataclouder** [vmware/go-vcloud-director#246]
Currently, you can set the storage profile for a VM only using `vdc.ComposeVapp`, which is the legacy method to create an implicit VM inside a vApp.

Adding a VM using `vapp.AddVM`, instead, lacks the ability of setting the storage profile.
We should create a new function that can deal with all the parameters that previously were handled by `ComposeVapp`

This issue affects the ability of creating VMs separately from vApps in terraform-provider-vcd

**Comment by Didainius** [comment]
We now have vApp.AddRawVM which accepts full VM configuration for those in need
