### ISSUE TITLE
Add ability to get all virtual servers/pools from NSX

### ISSUE THREAD

**Issue by voyvodov** [vmware/go-vcloud-director#265]
It will be good to have method to get all virtual servers configured on the NSX load balancer instead of only looking by id/name.
This could help us to get all used IPs for an example or make checks if IP:Port combination is already in used (in case we want to create 2 VS on the same IP, but different ports).

This should be pretty easy to implement since all VS are already get and then filtered out by name/id.

**Comment by voyvodov** [comment]
Already implemented

**Comment by Didainius** [comment]
Just adding a message that this was for NSX-V. NSX-T Pools are in progress.
