### ISSUE TITLE
External network doesn't able to be createad

### ISSUE THREAD

**Issue by slavaavr** [vmware/go-vcloud-director#279]
Hi there. Recently I came across that current version of library is not able to create external network. The thing is the line associated with network configuration -  https://github.com/vmware/go-vcloud-director/blob/master/govcd/system.go#L623 is not fully correct. Regarding to the vCloud Director API documentation (p.360), internal fields of network configuration must have xml prefix - `vcloud`, but they haven't. Thus, generated xml bodies are not valid.

**Comment by vbauzysvmware** [comment]
Hi @slavaavr,

Could you provide us HCL example you are runing. Also terraform runing/crash log and to better understand issue we need more logs from go-vcloud-director which should be enabled.
How to enable is mentioned in documentation: https://www.terraform.io/docs/providers/vcd/index.html - parameters logging, logging_file.

**Comment by slavaavr** [comment]
@vbauzysvmware is it ok if I provide you golang config I am using with? (I don't use terraform)

**Comment by lvirbalas** [comment]
Hi @slavaavr , curious, are you creating some Go tool based on go-vcloud-director?

CC: @dataclouder @Didainius

**Comment by vbauzysvmware** [comment]
Yes, @slavaavr, such example is enough. Thank you

**Comment by dataclouder** [comment]
Please have a look at the sample code linked below, and see if you can create an external network using this snippet as guideline:

https://github.com/vmware/go-vcloud-director/blob/master/govcd/externalnetwork_test.go#L77

**Comment by slavaavr** [comment]
@lvirbalas, yep, this is for work.

**Comment by slavaavr** [comment]
@vbauzysvmware, glad to hear it

**Comment by slavaavr** [comment]
@dataclouder thank you very much.  I did confused a bit, but now I've realised where the problem was: it's because of the lack 'Xmlns: vcdtypes.XMLNamespaceVCloud' field in the 'NetworkConfiguration' struct. 
__
So, thanks everyone!

**Comment by vbauzysvmware** [comment]
@slavaavr Glad to here :)

I wonder, is #280 still needed?

**Comment by slavaavr** [comment]
@vbauzysvmware, I closed the PR :)

**Comment by vbauzysvmware** [comment]
> @vbauzysvmware, I closed the PR :)

@slavaavr  thank you :)
