### ISSUE TITLE
Support working with sub allocated ip addresses within edge

### ISSUE THREAD

**Issue by slavaavr** [vmware/go-vcloud-director#286]
Hi there. It seems that current version of library does not support working with edge sub allocated ip addresses. So I reckon this functionality is needed.

**Comment by Didainius** [comment]
@slavaavr , the API is not the clearest thing, but it should support it. Double check the test: https://github.com/vmware/go-vcloud-director/blob/master/govcd/system_test.go#L317

**Comment by Didainius** [comment]
In addition - you probably don't care much about Terraform, but having a peak at [this function](https://github.com/terraform-providers/terraform-provider-vcd/blob/master/vcd/resource_vcd_edgegateway.go#L595-L665) and its docs may give additional ideas

**Comment by Didainius** [comment]
I am closing it now, but feel free to reopen if you are looking for something else.

**Comment by slavaavr** [comment]
@Didainius thanks for your reply! I checked it, but unfortunately it's not that I searching for. I meant that there is no function for the case if I read edge configuration and then trying to change sub allocated ip addresses (e.g. append new range).

**Comment by Didainius** [comment]
@slavaavr, so you are looking for a possibility to perform update for existing edge gateway, right?
I would suspect https://github.com/vmware/go-vcloud-director/issues/202 is what you're interested in.

**Comment by slavaavr** [comment]
@Didainius, right. I see, thank you very much!
