### ISSUE TITLE
InstantiateVAppTemplate

### ISSUE THREAD

**Issue by jondunning** [vmware/go-vcloud-director#309]
Hi,

InstantiateVAppTemplate is configured to use 'MethodPut' instead of 'MethodPost'.

https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/operations/POST-InstantiateVAppTemplate.html

Thanks,

Jon

**Comment by dataclouder** [comment]
Hi
Thanks for reporting this issue.
The function `InstantiateVAppTemplate` is legacy code that does not appear to be in use.
It will be reviewed within the work planned for [Issue 502 in terraform-provider-vcd](https://github.com/terraform-providers/terraform-provider-vcd/issues/502)

Changing it now without specific tests in place would not be profitable.

Are you using this function for something that the rest of the SDK doesn't provide?

**Comment by jondunning** [comment]
Hi,

'InstantiateVAppTemplate' is still used in the vCD web UI. I had to reverse engineer this API call to get the functionality I require. 

If 'InstantiateVAppTemplate' is legacy how would I check this in the future? What are you referencing? Don't want to waste your time looking at issues with legacy code :)

I've arrived at this point mainly around deploying a new vApp from a template with the following characteristics;

1. Single API call to Deploy vApp from Template with Network configured and Guest Customizations
2. Naming the storage folder within the datastore correctly. (If I use other API methods every datastore folder is named as the template name)

What API method would you advise using instead?

Thanks,

Jon

**Comment by jondunning** [comment]
@dataclouder I've looked at your referenced terraform provider and have used the code from there and datastore is named correctly. I dont get the single API call i was after but I dont think this is a sticking point.

Thanks for your help

**Comment by dataclouder** [comment]
> `InstantiateVAppTemplate`  is still used in the vCD web UI.
Which UI are you referring to? Is it a public project? Please provide some context

**Comment by dataclouder** [comment]
More information on this issue. 
The unused function would promote a behavior (create one vApp in a single operation) that we are actively discouraging in the Terraform project. Therefore, we are thinking of **removing this function** altogether.
If there is a reason to keep (and patch it), please provide further information. As far as we are concerned, the functionality to create and modify VMs is already in the SDK, and we don't see a good reason to keep this function.

**Comment by jondunning** [comment]
Im certainly happy for you to remove it. I've got the functionality I require using code snippets from Terraform provider. 

Thanks for you help.
