### ISSUE TITLE
InstantiateVAppTemplate panic 

### ISSUE THREAD

**Issue by jondunning** [vmware/go-vcloud-director#311]
Receive `panic: runtime error: invalid memory address or nil pointer dereference` when calling InstantiateVAppTemplate.

This is caused by this line; 

`types.MimeInstantiateVappTemplateParams, "error instantiating a new template: %s", template, vapptemplate)`

If you change to the below all works fine;

`types.MimeInstantiateVappTemplateParams, "error instantiating a new template: %s", template, vapptemplate.VAppTemplate)`

PR to follow

**Comment by dataclouder** [comment]
See annotation in Issue #310

**Comment by dataclouder** [comment]
See discussion in issue #309
