### ISSUE TITLE
org.GetVDCByName

### ISSUE THREAD

**Issue by jonjesse** [vmware/go-vcloud-director#319]
When I try to build the sample code, I get the following:

root@c45e68aa20a1:/home/govcd_example# go build -o example.go 
# govcd_example
./example.go:58:30: not enough arguments in call to org.GetVDCByName
	have (string)
	want (string, bool)
root@c45e68aa20a1:/home/govcd_example# 

Looking at file org.go, there are two functions of interest:

func (org *Org) GetVdcByName(vdcname string) (Vdc, error) {
This is mentioned as deprecated:
// Deprecated: use org.GetVDCByName instead

func (org *Org) GetVDCByName(vdcName string, refresh bool) (*Vdc, error) {

This requires two inputs, but sample code only has 1 input. What should refresh bool be set to? What does 'refresh bool' do?

**Comment by dataclouder** [comment]
Thanks for the report. We will update the example soon.

`org.GetVDCByName` requires the VDC name, and a Boolean value saying whether we need to refresh the Org or not.
Given that the Org was retrieved a few lines before, we can safely pass `false`

For a more updated example, you can look into the `./samples` directory.

**Comment by jonjesse** [comment]
That worked, marking this as closed, thank you.
