### ISSUE TITLE
Is there a function support upload OVF in an URL format

### ISSUE THREAD

**Issue by guo1017138** [vmware/go-vcloud-director#321]
Hi experts,

When upload OVF template on vCloud GUI, I am able to give an URL which points to ovf/ova. Such like:
http://example.com/test.ovf

Seems like UploadOvf function only support local OVF file, is there a function can upload ovf to vCloud with an URL?

**Comment by vbauzysvmware** [comment]
Hi @guo1017138 current implementation supports local OVF files. URL can't be provided yet.

**Comment by guo1017138** [comment]
@vbauzysvmware , Thanks for confirmation. I will download OVF to local first in my code as a workaround.

**Comment by vbauzysvmware** [comment]
For reference when we implement this:
example of request

.../api/catalog/6482a320-9666-4361-85af-a22a9506a17f/action/upload

<root:UploadVAppTemplateParams xmlns:root="http://www.vmware.com/vcloud/v1.5" name="zabbix_appliance-5.0.2-ovf.tar.gz" sourceHref="https://cdn.zabbix.com/zabbix/appliances/stable/5.0/5.0.2/zabbix_appliance-5.0.2-ovf.tar.gz"><root:Description>https://cdn.zabbix.com/zabbix/appliances/stable/5.0/5.0.2/zabbix_appliance-5.0.2-ovf.tar.gz</root:Description></root:UploadVAppTemplateParams>

**Comment by cloudmaniac** [comment]
I agree, it would be awesome to have this feature.

**Comment by tsugliani** [comment]
Same here, would be very practical.

**Comment by cloudmaniac** [comment]
🥳
