### ISSUE TITLE
Query disk usage of vdc

### ISSUE THREAD

**Issue by Zhe-Shen** [vmware/go-vcloud-director#343]
Hi,

I'm struggling with querying disk usage of vdc. I found relevant structs are defined in `types.go`, such as `StorageUsedMB` in `VdcStorageProfile`:

```
type VdcStorageProfile struct {
	Xmlns                     string                         `xml:"xmlns,attr"`
	Name                      string                         `xml:"name,attr"`
	Enabled                   bool                           `xml:"Enabled,omitempty"`
	Units                     string                         `xml:"Units"`
	Limit                     int64                          `xml:"Limit"`
	Default                   bool                           `xml:"Default"`
	IopsSettings              *VdcStorageProfileIopsSettings `xml:"IopsSettingsint64"`
	StorageUsedMB             int64                          `xml:"StorageUsedMB"`
	IopsAllocated             int64                          `xml:"IopsAllocated"`
	ProviderVdcStorageProfile *Reference                     `xml:"ProviderVdcStorageProfile"`
}
```

But I could not figure out a way to get this struct through API. Does anyone have same quest but know how to achieve this?

**Comment by vbauzysvmware** [comment]
Hi @Zhe-Shen,

You can use GetStorageProfileByHref function to fetch types.VdcStorageProfile and you will find StorageUsedMB there.

**Comment by Zhe-Shen** [comment]
> Hi @Zhe-Shen,
> 
> You can use GetStorageProfileByHref function to fetch types.VdcStorageProfile and you will find StorageUsedMB there.

I forgot to upgrade this package, that's why I couldn't find the usage field. Thanks, I'll close this issue.
