### ISSUE TITLE
if vappTemplate.VAppTemplate.Status != -1 then recreate virtual machine

### ISSUE THREAD

**Issue by patsevanton** [vmware/go-vcloud-director#351]
Hello!
I try create vapp + virtual machine.
But sometimes get failed.
I remove virtual machine and create again.

log terraform:
```
Error: [VM creation] error adding VM: error instantiating a new VM: API Error: 500: [ dfe3914e-ef07-4b42-941c-66d3df746aa5 ] Unable to perform this action. Contact your cloud administrator.
on main.tf line 85, in resource "vcd_vapp_vm" "vma":
85: resource "vcd_vapp_vm" "vma" {
Error: error completing tasks: task did not complete successfully: 
```

Can i or somebody write code and push to go-vcloud-director "if vappTemplate.VAppTemplate.Status != -1 then recreate virtual machine" ?

https://github.com/vmware/go-vcloud-director/blob/master/govcd/vapp.go#L187

**Comment by Didainius** [comment]
@patsevanton,
There may be a lot of difference scenarios and these are tricky to generalize. I would actually create some wrapper function locally inside your project while consuming SDK to solve your specific need.

**Comment by Didainius** [comment]
I will close this for now as hard wiring such functions can be error prone project wise.
