### ISSUE TITLE
Add an "how to write a new test" guide

### ISSUE THREAD

**Issue by dataclouder** [vmware/go-vcloud-director#36]
Add a new guide explaining how to write a test that integrates into our suite.

The guide could be either stand-alone or a new section inside TESTING.md

Main topics:
* Which imports are needed;
* How to write a test function integrated into the existing suite;
* What is the structure of TestVCD and what contents to expect;
* What is [check.v1](https://labix.org/gocheck) and what it can do for us;
* Guidelines on testing code readability.

This issue depends on Issue#34, and should not start before its completion.

**Comment by lvirbalas** [comment]
This is a good idea. Please amend to the existing TESTING.md - we want a single testing experience and type of tests for now.

**Comment by dataclouder** [comment]
Added using PR #42
