### ISSUE TITLE
GetEdgeGatewayRecordsType (and potentially other resources) not paginating

### ISSUE THREAD

**Issue by CmdrSharp** [vmware/go-vcloud-director#363]
Recently ran into an issue when Terraforming (using https://github.com/vmware/terraform-provider-vcd) which led me to dig deeper into this.
The issue was that randomly, when creating routed networks, Terraform would complain that edge gateways which indeed exist, do not. It would error out as such:
```
Error: [routed network read] error retrieving edge gateway namegoeshere: [ENF] entity not found
```

When digging into this, I decided to clone your example code and simply run the following code at the end, to receive a list of which edges are retrieved.

```go
	edgeGatewayList, err := vdc.GetEdgeGatewayRecordsType(true)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	for _, ert := range edgeGatewayList.EdgeGatewayRecord {
		fmt.Println(ert.Name)
	}
```

This indeed only returned the first 25 (same order as if I ran the query against /api/admin/vdc/{vdc_id}/edgeGateways myself).

Perhaps this function (and maybe other resource functions that I suspect may have the same issue) should auto-paginate when required?

**Comment by dataclouder** [comment]
Fixed in PR #364
