### ISSUE TITLE
Possibility to get Metrics?

### ISSUE THREAD

**Issue by reski-rukmantiyo** [vmware/go-vcloud-director#366]
Hi All, just wondering is it possible to get metrics from govcd?
Since I already implment all of my integration with govcd, then last thing that i need to gather metrics (cpu usage, memory utilization, and also storage from govcd). 

If it's not possible, any hints for this?

**Comment by Didainius** [comment]
@reski-rukmantiyo ,
Nope - it is not possible at the moment. There are probably two options - either improve govcd library or look if `govmomi` can do it. (I suppose vSphere can provide more data as well)

**Comment by reski-rukmantiyo** [comment]
Thanks for your info. Lets close this issue. Thanks
