### ISSUE TITLE
gvcd/vdc::ComposeRawVApp doesn't handle vApp creation requests correctly

### ISSUE THREAD

**Issue by Beshman420** [vmware/go-vcloud-director#386]
The task being returned by the api is direct reference to the vApp NOT the creation task.

This can cause error 400 issues as the vApp has not finished resolving before trying to add networks or guest properties.

When running task.WaitTaskCompletion() with the current "task", the status of the task is referencing the vApp status, not a running task status and will skip all the checks for "queued", "running" and "prerunning"

[govcd/vcd.go](https://github.com/vmware/go-vcloud-director/blob/61bd437c7d1e46aece322575453174aae60a7d5f/govcd/vdc.go#L467)

Fix (from L#484)

```
//Returns the newly create vApp
vapp, err := vdc.client.ExecuteTaskRequest(vdcHref.String(), http.MethodPost,
                      types.MimeComposeVappParams, "error instantiating a new vApp:: %s", vcomp)	

if err != nil {		
    return fmt.Errorf("error executing task request: %s", err)
}
 
//Only one task will be in progress for a vapp at this point
createTaskHref := vapp.Task.Tasks.Task[0].HREF

//Get task handling vApp creation
task, err := vdc.client.ExecuteTaskRequest(createTaskHref, http.MethodGet,
                      "", "error retreiving vApp task:: %s", vcomp)	

if err != nil {		
    return fmt.Errorf("error retreiving vApp task: %s", err)
}

err = task.WaitTaskCompletion()
if err != nil {		
    return fmt.Errorf("error performing task: %s", err)	
}

return nil


 
 ```

**Comment by dataclouder** [comment]
Thanks for bringing this issue to our attention.
This is indeed a bug ([/action/composeVapp](https://code.vmware.com/apis/1046/vmware-cloud-director/doc/doc/operations/POST-ComposeVApp.html) returns a vApp, not a task), which has stayed undetected for over 5 years.
We will publish a fix soon.
