### ISSUE TITLE
BUG: can't update EGW - there is no ownerRef field

### ISSUE THREAD

**Issue by lelvisl** [vmware/go-vcloud-director#395]
Struct from https://github.com/vmware/go-vcloud-director/blob/v2.12.1/types/v56/nsxt_types.go#L5 doesn't have field ownerRef. 

vCloud doesn't accept requests without this field
```
  "message": "[ 9ef3aa8c-e7fc-4377-9a63-e68479f83340 ] Invalid owner specified for edge gateway demo-kazaryan-nw-02-edge. Owner must be a organization vDC or vDC Group."
```
Result: method https://github.com/vmware/go-vcloud-director/blob/v2.12.1/govcd/nsxt_edgegateway.go#L137 not working at all.

Workaround: i continue to maintain my fork 🙂

**Comment by Didainius** [comment]
Hello, 
Thanks for the bug, but I need more details - which version of vcd and are tou overriding api version?

I think we do have tests and it used to work for all supported vcd versions.

**Comment by Didainius** [comment]
Is this the only thing that keeps you having the fork? We can surelly add this field here

**Comment by lelvisl** [comment]
No, i have some problems with quering vm, working with storage policies. https://github.com/vmware/go-vcloud-director/issues/373
And i want to do something with admin/non-admin objects. https://github.com/vmware/go-vcloud-director/issues/384
Some additional nsx-t funcs - (firewall,nat) i wrote earlier outside of this lib (using OpenApiGetItem and same client methods),   and preparing to migrate to library. 


If you can add this field - it will be very cool! (using `omitempty` - i think it will be backcompatible). 
Or i can make a PR.

**Comment by lelvisl** [comment]
About my project - internal project, some kind of aggregate web portal with IaaS (k8s/vcd) and some functions on top of them.

**Comment by Didainius** [comment]
> If you can add this field - it will be very cool! (using `omitempty` - i think it will be backcompatible).
> Or i can make a PR.

If you can just make that PR with a small note in changelog (.changes/v2.13.0)- no additional testing is required here from us so I will approve.



> About my project - internal project, some kind of aggregate web portal with IaaS (k8s/vcd) and some functions on top of them.

Sounds great!
