### ISSUE TITLE
How can I get a list of a VDC's OrgVDCNetworks?

### ISSUE THREAD

**Issue by jlearman** [vmware/go-vcloud-director#407]
We have vdc.GetVAppList() and vdc.QueryEdgeGatewayList(), but I don't see a way to get the list of networks.

Does Query() provide a generic way to do things like this?

**Comment by dataclouder** [comment]
`vdc.GetNetworkList()` returns a list of network information (`[]*types.QueryResultOrgVdcNetworkRecordType`)

**Comment by dataclouder** [comment]
Additionally, when you have a VDC object, you can get the list of networks from its structure: `vdc.Vdc.AvailableNetworks`

**Comment by jlearman** [comment]
Thanks!  I'm learning how to find things.  I assumed since it was based on vdc it would be in vdc.go.  My mistake!  Also thanks for the additional tip.

**Comment by jlearman** [comment]
Thanks!  I wonder why I didn't see this.  Perhaps I was looking at https://pkg.go.dev/github.com/Didainius/go-vcloud-director/v2/govcd, which is out of date.  I know better now.

**Comment by Didainius** [comment]
@jlearman ,
You were looking at a fork docs. You need to hit main repo - https://pkg.go.dev/github.com/vmware/go-vcloud-director/v2/govcd

It will contain latest released (neglecting the WIP alpha/beta versions)
