### ISSUE TITLE
The Pull Request template is easy to miss

### ISSUE THREAD

**Issue by lvirbalas** [vmware/go-vcloud-director#41]
When you do a PR the commit message is copied over automatically into the PR message as can be seen below. The .github/PULL_REQUEST_TEMPLATE.md appears at the bottom and is easy to miss or even submit together with the message. We need to emphasise and put more attention to it.

![pr template merges with the commit message](https://user-images.githubusercontent.com/11330689/44465318-e1f91b80-a625-11e8-8f26-83f390d7ffae.png)

**Comment by dataclouder** [comment]
Fixed by PR #31
