### ISSUE TITLE
Issue with setting the authorization token in the client using refresh tokens

### ISSUE THREAD

**Issue by Anirudh9794** [vmware/go-vcloud-director#446]
### Describe the bug

We are consuming GoVCD as part of CSI and CPI for Cloud Director. We support refresh token (or api token) based authentication for CSI and CPI.
Here is an example snippet
```
err = vcdClient.SetToken(config.Org, govcd.ApiTokenHeader, config.RefreshToken)
if err != nil {
	ERROR
}
```
The org to which the user belongs can be different from the org in which CSI or CPI are running (For example when CSI and CPI is using system admin credentials but are running as part of a tenant org)
The information about what org the user belongs to cannot be derived just by looking at the refresh token alone. This makes the function signature a little bit confusing to use as `userOrg` is a required parameter which is not known at the time of login.

I also observe that `org` is a required parameter as the URL to which the requests need to be made for provider and tenant users are different and this is making `org` a required parameter for `SetToken()`

To fix this issue we can have a workaround with a fallback with something like
```
err = vcdClient.SetToken("system", govcd.ApiTokenHeader, config.RefreshToken)
if err != nil {
	klog.Infof("failed to set authorization token in vcdClient as a provider. retrying as a tenant user")
	// since getting token for sysadmin failed, retry for a tenant user
	err = vcdClient.SetToken(org, govcd.ApiTokenHeader, config.RefreshToken)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to set authorization token in vcdClient: [%v]", err)
	}
}
```
or there needs to be a change in VCD API to handle the requests uniformly without expecting `userOrg` in the requests.

Can you please suggest which is the right way to work around this issue?

### Reproduction steps

```bash
1.Create a refresh token
2.Create a GoVCD client
3. Set authorization details for the refresh token using `vcdClient.SetToken(config.Org, govcd.ApiTokenHeader, config.RefreshToken)`
...
```

### Expected behavior

It would be ideal for us if we a function which doesn't expect an org parameter when setting authorization details for the client using a refresh token. Something like -
```
err = vcdClient.SetToken(govcd.ApiTokenHeader, config.RefreshToken)
```

**Comment by dataclouder** [comment]
The org parameter is needed because the API call for this kind of token requires it. Once you have a token, you need to know for which org it was issued. The call looks like this:

```
POST https://example.vmware.com/oauth/tenant/ORGNAME/token
```

When the token is for system, the call is

```
POST https://example.vmware.com/oauth/provider/token
```

Note that if you try to refresh a token that was created in a different organization, you get an error.

Please contact our team in slack (channel `#terraform-vcd` inside VMware) if you need more info.

**Comment by Didainius** [comment]
This was resolved as confirmed by @Anirudh9794
