### ISSUE TITLE
Figure out steps to make pr to hashicorp

### ISSUE THREAD

**Issue by auppunda** [vmware/go-vcloud-director#45]
@dataclouder @lvirbalas @hodgesrm @vbauzysvmware 
As a team we need to figure out what are the steps to be done before we can make a pr to hashicorp. This will give us an idea of what are the next steps for the project.

**Comment by auppunda** [comment]
I think the first step is cleaning the test suite. After that it is up in the air

**Comment by lvirbalas** [comment]
@auppunda do all of the existing Terraform changes lie in your fork currently?

**Comment by vbauzysvmware** [comment]
We are passed this point.
