### ISSUE TITLE
vdc.GetMetadata() has index issues when accessing the vdcs as a system org user

### ISSUE THREAD

**Issue by bogi0704** [vmware/go-vcloud-director#461]
### Describe the bug

I am using the vdc.GetMetadata() funtion as a user belonging to the system organization. I get the following error when calling this as a system user:
```
runtime error: index out of range [1] with length 1
```
This is happening because the function GetMetadata() uses the function getAdminVdcURL to get the admin url. But the url this function gets is already an admin url, since I am accessing the Metadata as a system user.

### Reproduction steps

```bash
1. Authenticate as a system org user
2. try to call vdc.GetMetadata()
```

### Expected behavior

The vdc.GetMetadata() should be able to distinguish if it needs to get the admin url or just use the one that the vdc object has.

### Additional context

I will open a pull request to fix this issue.

**Comment by adambarreiro** [comment]
Closing as done in #473
