### ISSUE TITLE
Edge QoS profile switching (rate limiting)

### ISSUE THREAD

**Issue by igor2104** [vmware/go-vcloud-director#472]
### Is your feature request related to a problem? Please describe.

How can I change a QoS profile of EDGE router (rate limitting) in vCloud Director?

https://developer.vmware.com/apis/vmware-cloud-director/latest/edge-gateway-qo-s/

### Describe the solution you'd like

Functions to retrieve and update the Edge Gateway Rate Limiting (QoS) configuration

**Comment by Didainius** [comment]
Hello, there is no ready made function yet, but you could always create a type on your own and use openapi low level functions to make requests. You can check it in:
govcd/openapi.go
samples/openapi/main.go
