### ISSUE TITLE
Allow ISOs with UDF filesystems to be uploaded with UploadMediaImage

### ISSUE THREAD

**Issue by rdavisunr** [vmware/go-vcloud-director#474]
### Is your feature request related to a problem? Please describe.

When attempting to upload an ISO with a [UDF ](https://wiki.osdev.org/UDF) filesystem, I received an error that stated: `file header didn't match ISO standard`

Tracked this error down to the [verifyIso](https://github.com/vmware/go-vcloud-director/blob/e1ba1526d24d94459c17e35f25bdb37887d7f057/govcd/media.go#L263) function in media.go which subsequently calls [verifyHeader](https://github.com/vmware/go-vcloud-director/blob/e1ba1526d24d94459c17e35f25bdb37887d7f057/govcd/media.go#L292), which only allows CD001 in the header (only allowing a ISO with an ISO 9660 filesystem).

Can ISOs with UDF filesystems also be supported?

### Describe the solution you'd like

Modify verifyHeader to allow [UDF](https://wiki.osdev.org/UDF) in addition to ISO 9660.

### Describe alternatives you've considered

For now, I reverted to creating ISOs in [ISO 9660](https://wiki.osdev.org/ISO_9660) with [Joliet ](https://wiki.osdev.org/Joliet) for support of longer filenames.

**Comment by vbauzysvmware** [comment]
Hi, @rdavisunr could share such a file for testing?

**Comment by rdavisunr** [comment]
@vbauzysvmware  - sure, ISO is in the attached zip. 

For the sake of example, the ISO contains a couple of directories and a binary file (notepad++ installer).

[udf-example.zip](https://github.com/vmware/go-vcloud-director/files/8773571/udf-example.zip)

**Comment by vbauzysvmware** [comment]
@rdavisunr thank you :)

**Comment by vbauzysvmware** [comment]
Hey @rdavisunr 

If you want to try now, then you can build from master the provider. 
Change will be released with 3.7.0 version :)
