### ISSUE TITLE
Unable to instantiate new VM 

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [vmware/go-vcloud-director#475]
### Describe the bug

Getting the following error when I try to create a new VM using `AddNewVMWithComputePolicy`. 

```
"API Error: 400: The parameter is not supported in the current context: InstantiationParamsType"
```

### Reproduction steps

```bash
1. Authenticate 
2. Try to call `vapp.AddNewVMWithComputePolicy`
```

### Expected behavior

Should be able to create a new VM.

**Comment by dataclouder** [comment]
Could you add more info, please?

* Which VCD version
* Repeat the request with [logging enabled](https://github.com/vmware/go-vcloud-director/blob/main/util/LOGGING.md) and report both request and response from the log file (use a gist if the output is too big)

**Comment by Didainius** [comment]
@ahmedwaleedmalik , I am closing this now as it has been too long without input. We believe this functionality to be working as we have tested and usage of it ourselves.
