### ISSUE TITLE
API Error: 406: The request has invalid accept header: Invalid API version requested. Supported API versions are:

### ISSUE THREAD

**Issue by prologic** [vmware/go-vcloud-director#477]
### Describe the bug

Running sample code found in the [README](/README.md) of this repo results in the following error:

```#!console
$ ./list-orgs
FATA[0000] error getting orgs                            error="error getting list of organizations: API Error: 406: The request has invalid accept header: Invalid API version requested. Supported API versions are: [37.0.0-alpha, 36.3, 36.2, 36.1, 36.0, 35.2, 35.0, 34.0, 33.0 [D], 32.0 [D], 31.0 [D]] ([D] indicates deprecated versions)"
```

- vCloud Director: 10.3.3

What other information do you need? I can provide sample code, but it is not much different to the samples code found in this repo.

### Reproduction steps

```bash
1. Build some sample code and call client.GetOrgList()
2. Observe the error above
```

### Expected behavior

No API error and a valid response.

**Comment by dataclouder** [comment]
Thanks for your report.
I tried the sample code from the README, and it works for me.
Here's how I ran it:

```
./example my-org-admin ORG_PASSWORD my-org sample.eng.vmware.com vdc-my-org
```

Where `my-org` is a non-system organization, and `vdc-my-org` is a VDC within `my-org`.

To run it as `list_orgs` , please modify the `main()` function as follows, and run as System administrator

```
func main() {
	if len(os.Args) < 5 {
		fmt.Println("Syntax: example user password System VCD_IP ")
		os.Exit(1)
	}
	config := Config{
		User:     os.Args[1],
		Password: os.Args[2],
		Org:      os.Args[3],
		Href:     fmt.Sprintf("https://%s/api", os.Args[4]),
		Insecure: true,
	}

	client, err := config.Client() // We now have a client
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	orgs, err := client.GetOrgList()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for _, org := range orgs.Org {
		fmt.Printf("%-30s %s\n", org.Name, org.HREF)
	}
}

```

Sample run:
```
./example administrator ADMIN_PASS System sample.eng.vmware.com 
```

**Comment by prologic** [comment]
I'll try this again, I suspect I'm getting bitten by vCloud Director and it's inability to return back correct and meaningful error codes. At least other things I was working lead me down this path... I'll report back.

**Comment by prologic** [comment]
Confirmed. vCloud Director returns an erroneous error when you login to the API with the wrong username/password. Instead of reporting something that looks like an "authentication failure" is returns "entity not found" 🤦‍♂️

TIL

**Comment by prologic** [comment]
Sorry for the bad report 😅
