### ISSUE TITLE
Upload a Catalog Item

### ISSUE THREAD

**Issue by lvirbalas** [vmware/go-vcloud-director#50]
We need ability to upload OVAs to the catalog. The implementation is not trivial, because they way vCD API works. You first have to extract the OVA, because vCD first needs the OVF description which is inside. Then vCD returns a set of links (which represent the `References->File` entries in the OVF XML), to which you upload each file separately.

In addition to the basic OVA upload, the following is also needed:

1. Support chunked OVA files.
2. Wait for the vCD to finish the import after uploading (this is above what `pyvcloud` does Today).
3. Utilise existing Task mechanism.
4. Report percentage progress.

**Comment by vbauzysvmware** [comment]
Things todo:
    Error handling return within xml of response
    Utilise existing Task mechanism.
    Report percentage progress
    Remove lock to xml first element
    Better error handling
    Missing tests
    Verify that "sanitizedName" func is enough to cover security issue -> See vmware/pyvcloud#268.

**Comment by vbauzysvmware** [comment]
Additional things after trying upload with progress:
Check against nil catalog
Investigate how it works with admin org catalog (works with standard user catalog)
Clean temp folder
Investigate to use system temp folder(It's possible that the directory containing the OVA is not writable, or users may not want to write there. We need to check whether the directory exists, and remove old files. Finally, we need to remove the files after an upload (successful or not)  we need to compare the file size 
Check files: from the tarball header with the size we have extracted

**Comment by vbauzysvmware** [comment]
Check if multiupload to same instance is working.

**Comment by vbauzysvmware** [comment]
> Two more checks:
> 
>     * [IMPORTANT] Look whether the catalog item already exists, so that we will avoid cryptic error messages when we try to upload;
> 
>     * Recover from a previous failure, when the catalog item is created, but we couldn't upload anything because of some error. [Optional, as if everything is checked correctly, we should not find ourselves in this predicament.]
I added check against existing existing item name as user won't understand 500 error with "contact administrator" message. IMHO, there is not point having recovering procedure of previous failure as we won't be able to see if it was govcd or any system or user manual tasks which hanging or failed. So deleting item with error or which is waiting is up to user to manage. API will return error that item already exist.

**Comment by vbauzysvmware** [comment]
Regarding multi upload: works fine as progress variable is local function variable and not shared between uploads. Mutex or other solution isn't needed as progress not shareable.

**Comment by vbauzysvmware** [comment]
Regarding multi upload: works fine as progress variable is local function variable and not shared between uploads. Mutex or other solution isn't needed as progress not shareable.

**Comment by vbauzysvmware** [comment]
Note Regarding admin connection. With administrator connection (organization system) organization search GetOrgByName will return empty as such organization doesn't exist and it's true, it's internal kind'a. And system "organization" doesn't have catalogs so upload isn't possible. So there is one way to upload to catalog item is to create vCD organization, user for it (with it to connect) and catalog where to upload.

**Comment by vbauzysvmware** [comment]
Done.

**Comment by vbauzysvmware** [comment]
Done
