### ISSUE TITLE
Ability for AdminOrg objects to call org functions

### ISSUE THREAD

**Issue by auppunda** [vmware/go-vcloud-director#53]
We need to discuss whether we want to fill up the org variable as well in the admin org. It will take an extra rest api call to get but it will enable users to be able to make calls to org functions as well. This is probably the closest we can get to pure inheritance.

**Comment by hodgesrm** [comment]
Hi @auppunda, can you illustrate with a code example the behavior you are aiming for?  Please include the client view as well as the changes you would like to make internally.  Thanks!

**Comment by auppunda** [comment]
<img width="674" alt="screen shot 2018-08-23 at 5 14 34 pm" src="https://user-images.githubusercontent.com/10393799/44558280-13421c00-a6f8-11e8-9a12-2bae1f10ccee.png">

**Comment by auppunda** [comment]
Internally one solution to this would be to change the function GetAdminOrgByName to also fill up the Org variable. Another solution is to have an flag whether the object is admin or non admin. If an org function is called, it checks If it is admin, and if it is, it changes the way the function is implemented.
<img width="704" alt="screen shot 2018-08-23 at 5 15 50 pm" src="https://user-images.githubusercontent.com/10393799/44558299-37056200-a6f8-11e8-9b86-e31fada4cbc2.png">

**Comment by hodgesrm** [comment]
Thank you.  What would happen if the account does not have privileges on orgs?  This does not look like a common tenant case, only the vCD sysadmin.

In general I think we may make ourselves unhappy by doing too much stuff under the covers.  It's better remain a thin veneer over the REST API. I would only optimize this if it leads to a lot of extra work for client code, which does not seem the case here.

**Comment by auppunda** [comment]
yes its vcd sysadmin case. I a not sure what happens if the account doesn't have privileges on the org its fetching. I assume it would be an error but I can test that out

**Comment by hodgesrm** [comment]
It will bomb, hopefully with a coherent error.  

Based on this discussion I would not optimize this flow.  Features like adding VDC operations seem a higher priority for now.

**Comment by auppunda** [comment]
yes definitely not a high priority

**Comment by auppunda** [comment]
Fixed with commit c58e060
